export * from './welcome';
export * from './about';
export * from './providers';
export * from './established-patients';
export * from './new-patients';
export * from './insurance';
export * from './resources';
export * from './contact';
export * from './direct-primary-care';